version: "3.7"

services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: master
      MYSQL_DATABASE: sample
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepass
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/db.sql:/docker-entrypoint-initdb.d/db.sql
    command: --init-file /docker-entrypoint-initdb.d/db.sql
    
  webpage:
    depends_on:
      - database
    build: .
    ports:
      - "3000:80"
    restart: always

volumes:
  db_data: {}